# Generated by Django 3.1.1 on 2020-10-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webNLP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtokollFach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fachbereich', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='Experimente',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='Thema',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='Theorie',
            field=models.CharField(max_length=300),
        ),
    ]
